### ISSUE TITLE
fails implementation 

### ISSUE THREAD

**Issue by HusseinAliF** [intmainreturn00/grapi#1]
ERROR: Failed to resolve: com.github.intmainreturn00:grapi:1.1

**Comment by intmainreturn00** [comment]
Thanks for the interest to the library! Did you add jitpack repo url into your build Gradle?

**Comment by HusseinAliF** [comment]
no, and I will learn kotlin first to continue

**Comment by intmainreturn00** [comment]
It also can be used from Java)
