### ISSUE TITLE
Authentication not working.

### ISSUE THREAD

**Issue by shubhamnandanwar** [intmainreturn00/grapi#5]
Goodreads has restricted its API. I think you should put this in the ReadMe section.
Let me know if it's not working for you as well.

Reference: https://www.goodreads.com/group/show/8095-goodreads-developers

**Comment by intmainreturn00** [comment]
> Since Goodreads [retire](https://www.goodreads.com/api) their api, this project should be considered deprecated as well. 🛑🥲
